// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz.Infrastructure.Data.EF;

#nullable disable

namespace Quiz.Infrastructure.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    partial class QuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quiz.Core.Models.Kviz", b =>
                {
                    b.Property<int>("KvizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KvizId"));

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KvizId");

                    b.ToTable("Kviz");
                });

            modelBuilder.Entity("Quiz.Core.Models.Pitanje", b =>
                {
                    b.Property<int>("PitanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PitanjeId"));

                    b.Property<int>("KvizId")
                        .HasColumnType("int");

                    b.Property<string>("Odgovor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PitanjeId");

                    b.HasIndex("KvizId");

                    b.ToTable("Pitanje");
                });

            modelBuilder.Entity("Quiz.Core.Models.RecikliranoPitanje", b =>
                {
                    b.Property<int>("RecikliranoPitanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecikliranoPitanjeId"));

                    b.Property<string>("Odgovor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecikliranoPitanjeId");

                    b.ToTable("RecikliranoPitanje");
                });

            modelBuilder.Entity("Quiz.Core.Models.Pitanje", b =>
                {
                    b.HasOne("Quiz.Core.Models.Kviz", "kviz")
                        .WithMany("Pitanja")
                        .HasForeignKey("KvizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kviz");
                });

            modelBuilder.Entity("Quiz.Core.Models.Kviz", b =>
                {
                    b.Navigation("Pitanja");
                });
#pragma warning restore 612, 618
        }
    }
}
